Repository appwrite/console, pull requests merged in 2023-02, with the labels that each got.

#247 Fix: file deletion text
  src/routes/console/project-[project]/storage/bucket-[bucket]/file-[file]/+page.svelte
Labels: bug

#232 Chore: upgrade sveltekit and dependencies
  package-lock.json
  package.json
  src/lib/actions/analytics.ts
  src/lib/components/card.svelte
  src/lib/components/dropListLink.svelte
  src/lib/components/eventModal.svelte
  src/lib/components/searchQuery.svelte
  src/lib/elements/forms/button.svelte
  src/lib/elements/forms/inputSecret.svelte
  src/lib/elements/pill.svelte
  src/lib/elements/table/rowButton.svelte
  src/lib/helpers/vitals.ts
  src/lib/layout/logs.svelte
  src/lib/stores/pagination.ts
  src/routes/+layout.svelte
  src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte
  tests/unit/layout/wizard.test.ts
  tests/unit/setup.ts
  vite.config.js
Labels: enhancement

#257 Refactor: API Key forms
  src/routes/console/project-[project]/overview/keys/[key]/+page@project-[project].svelte
  src/routes/console/project-[project]/overview/keys/[key]/updateExpirationDate.svelte
  src/routes/console/project-[project]/overview/keys/expirationInput.svelte
  src/routes/console/project-[project]/overview/keys/wizard/step1.svelte
Labels: bug, enhancement

#218 Refactor Event Modal
  .eslintrc.cjs
  src/lib/actions/selectionStart.ts
  src/lib/components/copy.svelte
  src/lib/components/eventModal.svelte
  src/lib/constants.ts
  src/lib/helpers/array.ts
  src/lib/helpers/string.ts
  src/routes/console/project-[project]/functions/function-[function]/settings/+page.svelte
  src/routes/console/project-[project]/functions/function-[function]/settings/updateEvents.svelte
  tsconfig.json
Labels: enhancement

#216 Feat: empty arrays UI
  src/lib/actions/tooltip.ts
  src/lib/elements/forms/inputCheckbox.svelte
  src/lib/elements/forms/inputDateTime.svelte
  src/lib/elements/forms/inputNumber.svelte
  src/lib/elements/forms/inputSelect.svelte
  src/lib/elements/forms/inputTags.svelte
  src/lib/elements/forms/inputText.svelte
  src/lib/helpers/object.ts
  src/lib/helpers/string.ts
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/[[page]]/+page.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/createDocument.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attribute.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributeForm.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/boolean.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/datetime.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/enum.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/integer.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/document.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/store.ts
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/wizard/step1.svelte
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/wizard/store.ts
  tests/unit/elements/inputText.test.ts
  tests/unit/helpers/object.test.ts
Labels: enhancement

#274 Refactor: API key page design details
  src/lib/elements/forms/inputSelect.svelte
  src/lib/helpers/date.ts
  src/routes/console/project-[project]/overview/keys/[key]/+page@project-[project].svelte
  src/routes/console/project-[project]/overview/keys/[key]/updateExpirationDate.svelte
  src/routes/console/project-[project]/overview/keys/expirationInput.svelte
  src/routes/console/project-[project]/overview/keys/scopes.svelte
  tests/unit/helpers/date.test.ts
Labels: enhancement

#246 Feat: function execution timer
  src/lib/actions/timer.ts
  src/routes/console/project-[project]/functions/function-[function]/[[page]]/+page.svelte
  src/routes/console/project-[project]/functions/function-[function]/executions/[[page]]/+page.svelte
  tsconfig.json
Labels: enhancement

#282 Feat: add success alert on feedback
  src/lib/components/feedbackGeneral.svelte
Labels: enhancement

#285 Refactor: Session length default unit
  src/lib/helpers/timeConversion.ts
  src/routes/console/project-[project]/auth/security/+page.svelte
  src/routes/console/project-[project]/auth/security/updateSessionLength.svelte
  src/routes/console/project-[project]/auth/security/updateSessionsLimit.svelte
  src/routes/console/project-[project]/auth/security/updateUsersLimit.svelte
  tests/unit/helpers/timeConversion.test.ts
Labels: enhancement

#256 Fix: Flutter platform wizard persistence
  src/routes/console/project-[project]/overview/platforms/wizard/apple/step1.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte
Labels: bug

#293 refactor: more default units
  src/lib/helpers/sizeConvertion.ts
  src/lib/helpers/unit.ts
  src/lib/helpers/withPrevious.ts
  src/routes/console/project-[project]/auth/security/updateSessionLength.svelte
  src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte
  src/routes/console/project-[project]/storage/bucket-[bucket]/settings/updateMaxFileSize.svelte
  tests/unit/helpers/unit.test.ts
  tests/unit/helpers/withPrevious.test.ts
Labels: enhancement

#320 Refactor: wizard spacings
  src/lib/layout/wizardStep.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/android/step2.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/apple/step3.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/flutter/step2.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/flutter/step3.svelte
  src/routes/console/project-[project]/overview/platforms/wizard/web/step2.svelte
Labels: enhancement

#319 Fix: falsy values showing up as n/a
  src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/[[page]]/+page.svelte
Labels: bug

#249 Feat: add console footer
  src/lib/actions/analytics.ts
  src/lib/layout/footer.svelte
  src/lib/layout/shell.svelte
  src/lib/stores/sdk.ts
  src/routes/+layout.svelte
  src/routes/console/+layout.svelte
  src/routes/console/+layout.ts
  src/routes/console/store.ts
  src/routes/register/invite/[slug]/+page.svelte
  svelte.config.js
Labels: enhancement

#305 Fix: remove avatars from database settings
  src/routes/console/project-[project]/databases/database-[database]/settings/+page.svelte
Labels: bug

#307 Fix: warning modal avatar color
  src/lib/components/modal.svelte
Labels: bug
