Repository appwrite/console, pull requests merged in 2024-10, with the labels that each got.

#1208 fix: allow address removal
  src/routes/(console)/account/payments/+page.ts
  src/routes/(console)/account/payments/billingAddress.svelte
  src/routes/(console)/account/payments/paymentMethods.svelte
  src/routes/(console)/organization-[organization]/billing/billingAddress.svelte
  src/routes/(console)/organization-[organization]/billing/deleteOrgPayment.svelte
  src/routes/(console)/organization-[organization]/billing/paymentMethods.svelte
  src/routes/(console)/organization-[organization]/billing/removeAddress.svelte
Labels: product / billing

#1245 feat: BAA and Soc-2
  src/lib/actions/analytics.ts
  src/routes/(console)/organization-[organization]/settings/+page.svelte
  src/routes/(console)/organization-[organization]/settings/BAA.svelte
  src/routes/(console)/organization-[organization]/settings/BAAModal.svelte
  src/routes/(console)/organization-[organization]/settings/Soc2.svelte
  src/routes/(console)/organization-[organization]/settings/Soc2Modal.svelte
Labels: product / billing

#1355 fix: page breaks on redirection
  src/lib/helpers/sizeConvertion.ts
  src/lib/helpers/unit.ts
  src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte
  src/routes/(console)/project-[project]/auth/security/updatePasswordDictionary.svelte
  src/routes/(console)/project-[project]/auth/security/updatePasswordHistory.svelte
  src/routes/(console)/project-[project]/auth/security/updatePersonalDataCheck.svelte
  src/routes/(console)/project-[project]/auth/security/updateSessionAlerts.svelte
  src/routes/(console)/project-[project]/auth/security/updateSessionLength.svelte
  src/routes/(console)/project-[project]/auth/security/updateSessionsLimit.svelte
  src/routes/(console)/project-[project]/auth/security/updateUsersLimit.svelte
  src/routes/(console)/project-[project]/auth/templates/+page.svelte
  src/routes/(console)/project-[project]/auth/templates/+page.ts
  src/routes/(console)/project-[project]/auth/templates/emailTemplate.svelte
  src/routes/(console)/project-[project]/functions/function-[function]/+page.svelte
  src/routes/(console)/project-[project]/messaging/topics/table.svelte
Labels: bug

#1466 Update resource for appwrite to appwrite migration
  src/lib/stores/migration.ts
  src/routes/(console)/(migration-wizard)/resource-form.svelte
Labels: product / migrations
